### ISSUE TITLE
Differentiate between waiting for user approval, and user's explicit denial. 

### ISSUE THREAD

**Issue by ChaseFlorell** [jamesmontemagno/Xamarin.Plugins#114]
On iOS (and Android soon), there's this weird state of gps where gps is not yet enabled, but hasn't been explicitly denied (or approved) by the user. Is there any way to detect this state and handle it differently (IE wait)?

Right now I've got a 60 second wait on `IsGeolocationEnabled` but we wait for it regardless of whether we're waiting for the user to approve, or just waiting till the timeout because they denied. This is problemmatic because I've also got an activity indicator on screen until the method exits.

**Comment by ChaseFlorell** [comment]
This is sorta what I came up with.

```csharp
        private async Task<Position> GetUsersCurrentLocation()
        {
            // don't bother.
            if (!_geolocator.IsGeolocationAvailable)
            {
                return null;
            }

            var geoEnabled = _geolocator.IsGeolocationEnabled;

            if (!geoEnabled)
            {
                var counter = 0;
                // try for 10 seconds in hopes that the user enables geo location.
                while (!geoEnabled && counter < 10)
                {
                    await Task.Delay(1000); // wait one second and try again.
                    geoEnabled = _geolocator.IsGeolocationEnabled;
                    counter++;
                }
            }

            try
            {
                if (geoEnabled)
                {
                    return await _geolocator.GetPositionAsync(10000); // 10 second timeout.
                }
                return null;
            }
            catch
            {
                return null;
            }
        }
```

**Comment by kolchy** [comment]
Are you sure this isn't to do with #115 that I just logged? I found that the position is only returned once the GetPositionAsync() call times out.

**Comment by tee-h** [comment]
This is not the same issue as #115.

I am having to implement the same workaround as @ChaseFlorell.  Upon first time use, my app attempts to use location.  Since my app has never asked the user for location access, the plug-in correctly shows the user the "give my app location permission" dialog box.  However, the rest of my code continues to execute since this prompt is asynchronous.  This means the location request attempt fails - ideally it should pause and wait for user input, or there should be an event fired when the user grants permission.

As described at the URL below, we need an enhancement that will bubble up the native iOS didChangeAuthorizationStatus event so we can fire a location request when the user authorizes location - instead of resorting to timers and loops:

http://nshipster.com/core-location-in-ios-8/

"Since this happens asynchronously, the app can’t start using location services immediately. Instead, one must implement the locationManager:didChangeAuthorizationStatus delegate method, which fires any time the authorization status changes based on user input."

I've noticed in the current code at Geolocator.Plugin.iOS/GeolocatorImplementation.cs that there's a private event:

private void OnAuthorizationChanged (object sender, CLAuthorizationChangedEventArgs e)
		{
			if (e.Status == CLAuthorizationStatus.Denied || e.Status == CLAuthorizationStatus.Restricted)
				OnPositionError (new PositionErrorEventArgs (GeolocationError.Unauthorized));
		}

Could we get this made as public and bubble up didChangeAuthorizationStatus into the PCL?  I'd love to take my Xamarin.Forms app live without having to resort to changing the UX or timers and loops.

**Comment by jamesmontemagno** [comment]
I would recommend using my new permissions plugin to handle this: motzcod.es/post/133939517717/simplified-ios-android-runtime-permissions-with
