### ISSUE TITLE
Geolocator Heading support on Android

### ISSUE THREAD

**Issue by zezioen** [jamesmontemagno/Xamarin.Plugins#140]
https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Geolocator/Geolocator/Geolocator.Plugin.Android/GeolocatorImplementation.cs

Heading support is disabled by code in Android, the code to check if heading support is available has been commented out. Can this be re-enabled? 

We're currently using the continuous update of the heading for our app but on Android it's not being reported properly (iOS reports it every time the device rotates and Google maps shows that such functionality is available on Android as well)

**Comment by jamesmontemagno** [comment]
I actually do return the Heading if it exists, however the Android one is very inaccurate and almost always returns 0, which is why we originally just said it wasn't supported. I am working on updating a compass plugin that would probably work nicer:

https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Geolocator/Geolocator/Geolocator.Plugin.Android/GeolocationSingleListener.cs#L125

**Comment by jamesmontemagno** [comment]
Compass Plugin: https://github.com/JarleySoft/Xamarin.Plugins/tree/master/Compass
