### ISSUE TITLE
Problem with new version (2.0) of connectivity plugin

### ISSUE THREAD

**Issue by fgiacomelli** [jamesmontemagno/Xamarin.Plugins#148]
Hello,
I'm using your plugin inside my xamarin Forms app.
When I call the CrossConnectivity.Current.IsConnected
I get this error:
System.NotImplementedExceptionThis functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

**Comment by jamesmontemagno** [comment]
Did you upgrade all of your NuGets to version 2.0? inside your PCL as well.

Also, which project type?

**Comment by fgiacomelli** [comment]
yes I do, thank you.
I'm discovering that with new version (I just upgraded also Visual 
studio 2015 to the new SP1) my app crash at startup with debugging 
enabling, and Xamarin Insight tell me that the problem is related to 
your plugin:

> *Message:*
>
> This functionality is not implemented in the portable version of this 
> assembly. You should reference the NuGet package from your main 
> application project in order to reference the platform-specific 
> implementation.
>
> *Stack Trace:*
> Plugin.Geolocator.CrossGeolocator.get_Current()

however if I launch it in release mode, without debugging, it works.
I think it's something related to this:
https://forums.xamarin.com/discussion/50195/release-build-doesnt-work-aot-module-errors
(only inverted), obviously I already rebooted machine, removed the app 
from device


Il 02/12/2015 18.45, James Montemagno ha scritto:

**Comment by jamesmontemagno** [comment]
What type of app are you trying? Is it Android? iOS?Windows?

Also this says Geolocator, not the connectivity. Did you install the Geolocator in all of your projects?

**Comment by jamesmontemagno** [comment]
I am having absolutely no issues at all here in debug mode.

**Comment by syedabidali** [comment]
Hi,
I have also faced this issue , when i call CrossConnectivity.Current.IsConnected from my PCL Project in debug mode..i am debugging though genymotion android vm

**Comment by MagnusJohansson** [comment]
@syedabidali , I also faced this exact error when calling ..IsConnected. Even after referencing the Connectivity plugin in the main project. After a Solution->Clean all, the error went away. This was on Xamarin Studio (v6) on a Mac, which is known for being a bit quirky, when everything else fails-> Clean All...

**Comment by Nathan187** [comment]
I too am getting this error.  Clean All, delete obj/bin folders...does not work.  All packages are up to date.  Anyone else having this issue?

**Comment by x2brjoy** [comment]
I am having this exact issue. Cleaning project did not help. My packages are updated.

**Comment by jamesmontemagno** [comment]
Doe anyone have a stacktrace of the error? you could put it on gist.github.com

**Comment by x2brjoy** [comment]
It is error from my side, was not importing the connectivity packages separately in IOS and android folder. So it is fixed now. Thanks.

**Comment by aneelmehta** [comment]
@jamesmontemagno 

I had the same problem.   Once I cleaned the solution and Rebuilt all projects it is **working now**.

**The error was** 

System.NotImplementedException: 
This functionality is not implemented in the portable version of this assembly.  
You should reference the NuGet package from your main application 
project in order to reference the platform-specific implementation.
  at at (wrapper dynamic-method) System.Object:3c9d8ea9-d4ba-4288-8249-b6cfa1d3f9f6 (intptr,intptr,intptr)
  at at (wrapper native-to-managed) System.Object:3c9d8ea9-d4ba-4288-8249-b6cfa1d3f9f6 (intptr,intptr,intptr)

**Comment by dottorp** [comment]
This issue seems due to this snippet of code:
`  static IMedia CreateMedia()
        {
#if PORTABLE
            return null;
#else
            return new MediaImplementation();
#endif
        }
`
CreateMedia() is called by the Current property. I'm knocking my head against this issue, too.

**Comment by jamesmontemagno** [comment]
@dottorp you must install the NuGet into all projects.

**Comment by Olivier-B** [comment]
Hi James,

I also have the same issue... 

- I started a new project (only Droid, UW, W8.1).
- I added Nuget Package: Xam.Plugin.Connectivity (v2.2.12) in all projects (Portable, Droid, UW, W8.1)
- Windows is working fine.... But Droid gives me the following stack trace

>>>>>>>>>>>>>
11-09 10:49:53.976 D/Mono    ( 3843): Assembly Ref addref HelloWorld[0xada16ac0] -> Plugin.Connectivity.Abstractions[0xada16280]: 3
Unhandled Exception:

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

11-09 10:50:00.852 D/Mono    ( 3843): DllImport attempting to load: '/system/lib/liblog.so'.
11-09 10:50:00.852 D/Mono    ( 3843): DllImport loaded library '/system/lib/liblog.so'.
11-09 10:50:00.852 D/Mono    ( 3843): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
11-09 10:50:00.852 D/Mono    ( 3843): Searching for '__android_log_print'.
11-09 10:50:00.852 D/Mono    ( 3843): Probing '__android_log_print'.
11-09 10:50:00.852 D/Mono    ( 3843): Found as '__android_log_print'.
11-09 10:50:00.857 I/MonoDroid( 3843): UNHANDLED EXCEPTION:
11-09 10:50:00.861 I/MonoDroid( 3843): System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
11-09 10:50:00.861 I/MonoDroid( 3843):   at Plugin.Connectivity.CrossConnectivity.get_Current () [0x0000d] in C:\projects\connectivityplugin\src\Connectivity.Plugin\CrossConnectivity.cs:23 
11-09 10:50:00.861 I/MonoDroid( 3843):   at HelloWorld.MainPage.updateLabel () [0x00001] in D:\Xamarin\Nov2016\HelloWorld\HelloWorld\HelloWorld\MainPage.xaml.cs:21 
11-09 10:50:00.861 I/MonoDroid( 3843):   at HelloWorld.MainPage..ctor () [0x0000f] in D:\Xamarin\Nov2016\HelloWorld\HelloWorld\HelloWorld\MainPage.xaml.cs:16 
11-09 10:50:00.861 I/MonoDroid( 3843):   at HelloWorld.App..ctor () [0x0000f] in D:\Xamarin\Nov2016\HelloWorld\HelloWorld\HelloWorld\App.xaml.cs:16 
11-09 10:50:00.861 I/MonoDroid( 3843):   at HelloWorld.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00027] in D:\Xamarin\Nov2016\HelloWorld\HelloWorld\HelloWorld.Droid\MainActivity.cs:23 
11-09 10:50:00.861 I/MonoDroid( 3843):   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <27c17fe440cf491ba8255bcefade6e02>:0 
11-09 10:50:00.861 I/MonoDroid( 3843):   at (wrapper dynamic-method) System.Object:bc9eb942-7ae8-48fd-a2b3-16d8d28d4b30 (intptr,intptr,intptr)
11-09 10:50:00.872 W/art     ( 3843): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
11-09 10:50:00.876 D/Mono    ( 3843): DllImport searching in: '__Internal' ('(null)').
11-09 10:50:00.876 D/Mono    ( 3843): Searching for 'java_interop_jnienv_throw'.
11-09 10:50:00.876 D/Mono    ( 3843): Probing 'java_interop_jnienv_throw'.
11-09 10:50:00.876 D/Mono    ( 3843): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.
>>>>>>>>

Hope this will help you identify and fix the issue...

**Comment by Olivier-B** [comment]
By the way, I had to check the following options in the manifest manually
ACCESS_NETWORK_STATE & ACCESS_WIFI_STATE

**Comment by Olivier-B** [comment]
I re-tested it with a <<Blank App (Xamarin.Forms Portable) project>> and it works fine.
I tested it with <<Blank XAML App (Xamarin.forms Portable) and I get the error describe above.

Hope this can help you :-)

**Comment by Olivier-B** [comment]
Sorry, 
I just see that my text is not as I expected.
-1- I tested with a Blank App (Xamarin.Forms Portable) project and it works fine
-2- I tested with a Blank XAML App (Xamarin.Forms Portable) and I have the error

**Comment by Ruddy2007** [comment]
Also running into this problem. Its a bit odd, didnt work in debug mode at all then tried release and it worked for a little bit but now back to not working. 

Not really sure what to do with this haha. Any news on this?

**Comment by jamesmontemagno** [comment]
I don't answer responses on here, you need to go to the new repo, you probably need to clean and rebuild.

**Comment by heavyBug** [comment]
Also running into this problem. But i rechecked all the projects if the plugin is added in all. Then i clean the Droid(Specific Project) and then clean all. It  worked for me.

Thanks to @MagnusJohansson

**Comment by carvah** [comment]
Got my project working with this solution:

- Install the latest version of Xam.Plugin.Geolocator
- Clean
- Rebuild

Done.
