### ISSUE TITLE
Would be nice to have a clear all settings method in CrossSettings

### ISSUE THREAD

**Issue by bmmathe** [jamesmontemagno/Xamarin.Plugins#274]
Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [ ] Bug
- [x ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [ ] Media
- [ ] Permissions
- [x ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.1.0

For debugging purposes it would be nice to have a way to clear all settings in the CrossSettings.Current object.  It would also be helpful in a "Delete Profile" scenario.

**Comment by Korayem** [comment]
I would say this is utterly important, not just in Debugging because for apps with authentication, we must clear all cache upon user's logout to ensure next user who'll login won't see any old cached data.

It can be done now through a foreach on list of cache keys, but a big "CLEAR'EM ALL" panic button will be lovely :)

**Comment by jamesmontemagno** [comment]
This issue was moved to jamesmontemagno/SettingsPlugin#6
