### ISSUE TITLE
System.MissingMethodException Method Android.GMS.Maps.MapView.get_Map Not Found

### ISSUE THREAD

**Issue by siwakornapichit** [jamesmontemagno/Xamarin.Plugins#353]
If I call function CrossGeolocator.Current.GetPositionAsync on Android Platform. It pop up error this message. I can not solve this problem.

Xam.Plugin.Geolocator Version 3.0.4 
Visual 2015 
Cross Platform Project PCL

Please Help.

**Comment by jamesmontemagno** [comment]
The geolocator plugin does not have any GMS inside of it. It most likely is something else in the code.

**Comment by hinojosachapel** [comment]
This is not Geolocator plugin responsibility, it's Xamarin.Forms.Maps's fault, because Google has removed method 'Android.Gms.Maps.MapView.get_Map'. More info at https://bugzilla.xamarin.com/show_bug.cgi?id=52625. I'm suffering the same pain in the ass trying to use Firebase. Waiting for the final solution from Xamarin Team.
